"""initial schema

Revision ID: 6108ef3356a6
Revises:
Create Date: 2026-04-21 11:46:54.268719

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6108ef3356a6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_config_key"), ["key"], unique=True)

    op.create_table(
        "correspondent_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paperless_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_type_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paperless_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processing_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("document_title", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("llm_provider", sa.String(), nullable=True),
        sa.Column("llm_model", sa.String(), nullable=True),
        sa.Column("llm_response", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("prompt_type", sa.String(), nullable=False),
        sa.Column("document_type_filter", sa.String(), nullable=True),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.Column("user_template", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paperless_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag_cache")
    op.drop_table("prompts")
    op.drop_table("processing_logs")
    op.drop_table("document_type_cache")
    op.drop_table("correspondent_cache")
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_key"))

    op.drop_table("config")
    # ### end Alembic commands ###
